name: Hub_Manager
version: '1.0-SNAPSHOT'
main: fr.GameOfFamous.hub_Manager.Hub_Manager
api-version: '1.20'
commands:
  spawn:
permissions:
  server.*:
    children:
      server.build: true
  cmd.*:
    children:
      cmd.setstaff: true
depend:
  - HellstyliaAPI
